spring.application.name=risk-issue-management-system

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/risk_issue_db
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
