spring.application.name=defect-tracking-system

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/defect_tracking_db
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
