spring.application.name=user-story-management-api

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/user_story_db
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
