version: "3.9"

services:

  mysql:

    image: mysql:8

    container_name: change-impact-mysql

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: change_impact_db

    ports:
      - "3306:3306"
